version: "3.9"
services:
  cdn:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app-workspace:cached
      - /app-workspace/node_modules
    command: ["node","server.js"]