version: "3.9"
services:
  cdn-main:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace:cached
      - /workspace/node_modules
    command: ["node","server.js"]